#ifndef ESTREEPACKAGE_GLOBAL_H
#define ESTREEPACKAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ESTREEPACKAGE_LIBRARY)
#  define ESTREEPACKAGESHARED_EXPORT Q_DECL_EXPORT
#else
#  define ESTREEPACKAGESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ESTREEPACKAGE_GLOBAL_H
